describe('pizza maker form', () => {
  it('name field', () => {
    cy.visit('http://localhost:3000/pizza')
    cy.get('[name="name"]').type('some text')
    cy.get('[name="name"]').should('have.value', 'some text')
  })
  it('Can check toppings', () => {
    cy.visit('http://localhost:3000/pizza')
    cy.get('#red-sauce').check()
    cy.get('#red-sauce').should('be.checked')
    cy.get('[value="white"]').check()
    cy.get('[value="white"]').should('be.checked')
    cy.get('[value="mystery"]').check()
    cy.get('[value="mystery"]').should('be.checked')
    cy.get('[name="ham"]').check()
    cy.get('[name="ham"]').should('be.checked')
    cy.get('[name="pepperoni"]').check()
    cy.get('[name="pepperoni"]').should('be.checked')
    cy.get('[name="onions"]').check()
    cy.get('[name="onions"]').should('be.checked')
    cy.get('[name="jalapenos"]').check()
    cy.get('[name="jalapenos"]').should('be.checked')
    cy.get('[name="pineapple"]').check()
    cy.get('[name="pineapple"]').should('be.checked')
  })
  it('can submit the form', () => {
    cy.visit('http://localhost:3000/pizza')
    cy.get('[name="name"]').type('some text in there')
    cy.contains('Place Order').click()
    cy.url().should('include', '/confirmation')
  })
})